In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\Supply Chain Dataset.csv",encoding='latin1')

In [4]:
df.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [5]:
df.shape

(180519, 53)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [7]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

Drop null and unwanted columns that were not helping in our analysis

In [8]:
unwanted_cols = [
    'Product Description', 'Product Status', 'Customer Password', 'Customer Email', 'Category Id', 'Customer Id', 'Department Id', 'Order Customer Id', 
    'Order Item Cardprod Id', 'Order Item Id', 'Product Card Id', 'Product Category Id', 'Customer Fname', 'Customer Lname', 'Customer Street',
    'Product Image', 'Order Zipcode'
]
df=df.drop(columns=unwanted_cols)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Name                  180519 non-null  object
 8   Customer City                  180519 non-null  object
 9   Customer Country               180519 non-null  object
 10  Customer Segment               180519 non-null  object
 11  Customer State                 180519 non-null  object
 12  Customer Zipcode               180516 non-null  float64
 13  Department Name                180519 non-null  object
 14  Latitude                       180519 non-null  float64
 15  Longitude                      180519 non-null  float64
 16  Market                         180519 non-null  object
 17  Order City                     180519 non-null  object
 18  Order Country                  180519 non-null  object
 19  order date (DateOrders)        180519 non-null  object
 20  Order Id                       180519 non-null  int64
 21  Order Item Discount            180519 non-null  float64
 22  Order Item Discount Rate       180519 non-null  float64
 23  Order Item Product Price       180519 non-null  float64
 24  Order Item Profit Ratio        180519 non-null  float64
 25  Order Item Quantity            180519 non-null  int64
 26  Sales                          180519 non-null  float64
 27  Order Item Total               180519 non-null  float64
 28  Order Profit Per Order         180519 non-null  float64
 29  Order Region                   180519 non-null  object
 30  Order State                    180519 non-null  object
 31  Order Status                   180519 non-null  object
 32  Product Name                   180519 non-null  object
 33  Product Price                  180519 non-null  float64
 34  shipping date (DateOrders)     180519 non-null  object
 35  Shipping Mode                  180519 non-null  object
dtypes: float64(13), int64(5), object(18)
memory usage: 49.6+ MB

Renaming column names

In [10]:
df.columns=df.columns.str.lower().str.replace(' ','_').str.replace('(','').str.replace(')','')

In [11]:
df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_city,customer_country,...,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,product_name,product_price,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,...,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,...,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,...,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,Smart watch,327.75,1/15/2018 11:24,Standard Class

In [12]:
df.order_date_dateorders

0         1/31/2018 22:56
1         1/13/2018 12:27
2         1/13/2018 12:06
3         1/13/2018 11:45
4         1/13/2018 11:24
               ...
180514     1/16/2016 3:40
180515     1/16/2016 1:34
180516    1/15/2016 21:00
180517    1/15/2016 20:18
180518    1/15/2016 18:54
Name: order_date_dateorders, Length: 180519, dtype: object

convert order_date column to proper format so that we can extract different parts from that column like month , year etc

In [13]:
df['order_date_dateorders'] = pd.to_datetime(df['order_date_dateorders'])

In [14]:
df.order_date_dateorders

0        2018-01-31 22:56:00
1        2018-01-13 12:27:00
2        2018-01-13 12:06:00
3        2018-01-13 11:45:00
4        2018-01-13 11:24:00
                 ...
180514   2016-01-16 03:40:00
180515   2016-01-16 01:34:00
180516   2016-01-15 21:00:00
180517   2016-01-15 20:18:00
180518   2016-01-15 18:54:00
Name: order_date_dateorders, Length: 180519, dtype: datetime64[ns]

In [15]:
df['order_year'] = df['order_date_dateorders'].dt.year
df['order_month'] = df['order_date_dateorders'].dt.month_name()

In [16]:
df=df.drop(columns=['benefit_per_order'])

Round the floating values to 2 decimal places

In [17]:
float_cols=df.select_dtypes(include=['float64']).columns
df[float_cols] = df[float_cols].round(2)

calculate actual delay in shipping

In [18]:
df['actual_delay']=df['days_for_shipping_real']-df['days_for_shipment_scheduled']

In [19]:
df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_city,customer_country,customer_segment,...,order_region,order_state,order_status,product_name,product_price,shipping_date_dateorders,shipping_mode,order_year,order_month,actual_delay
0,DEBIT,3,4,314.64,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Consumer,...,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,2/3/2018 22:56,Standard Class,2018,January,-1
1,TRANSFER,5,4,311.36,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Consumer,...,South Asia,Rajastán,PENDING,Smart watch,327.75,1/18/2018 12:27,Standard Class,2018,January,1
2,CASH,4,4,309.72,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Consumer,...,South Asia,Rajastán,CLOSED,Smart watch,327.75,1/17/2018 12:06,Standard Class,2018,January,0
3,DEBIT,3,4,304.81,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Home Office,...,Oceania,Queensland,COMPLETE,Smart watch,327.75,1/16/2018 11:45,Standard Class,2018,January,-1
4,PAYMENT,2,4,298.25,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Corporate,...,Oceania,Queensland,PENDING_PAYMENT,Smart watch,327.75,1/15/2018 11:24,Standard Class,2018,January,-2

Fixing encoding issues

In [20]:
def fix_char(text):
    if not isinstance(text, str):
        return text
    try:
        return text.encode('latin1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

string_cols = df.select_dtypes(include=['object']).columns
for col in string_cols:
    df[col] = df[col].apply(fix_char)

print(df['order_state'].unique()[:5])

['Java Occidental' 'Rajastán' 'Queensland' 'Guangdong' 'Tokio']

In [21]:
df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_city,customer_country,customer_segment,...,order_region,order_state,order_status,product_name,product_price,shipping_date_dateorders,shipping_mode,order_year,order_month,actual_delay
0,DEBIT,3,4,314.64,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Consumer,...,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,2/3/2018 22:56,Standard Class,2018,January,-1
1,TRANSFER,5,4,311.36,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Consumer,...,South Asia,Rajastán,PENDING,Smart watch,327.75,1/18/2018 12:27,Standard Class,2018,January,1
2,CASH,4,4,309.72,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Consumer,...,South Asia,Rajastán,CLOSED,Smart watch,327.75,1/17/2018 12:06,Standard Class,2018,January,0
3,DEBIT,3,4,304.81,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Home Office,...,Oceania,Queensland,COMPLETE,Smart watch,327.75,1/16/2018 11:45,Standard Class,2018,January,-1
4,PAYMENT,2,4,298.25,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Corporate,...,Oceania,Queensland,PENDING_PAYMENT,Smart watch,327.75,1/15/2018 11:24,Standard Class,2018,January,-2

Loading data to postgres sql database for further insights

In [22]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()
user=os.getenv('DB_USER')
password=os.getenv('DB_PASSWORD')
host=os.getenv('DB_HOST')
port=os.getenv('DB_PORT')
db_name=os.getenv('DB_NAME')

engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db_name}')

In [23]:
table_name='shipping'

df.to_sql(table_name, engine, if_exists='replace', index=False, chunksize=10000, method='multi')

print(f"Data successfully loaded into '{table_name}' in database '{db_name}'.")

Data successfully loaded into 'shipping' in database 'shipping'.